# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        black_args: ". --check --line-length 120"

    - name: Install dependencies
      run: |
        make install_ci
    - name: Run Unit Tests
      run: |
        make unit_test
    - name: Upload Coverage
      uses: codecov/codecov-action@v1.2.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
